config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "sales#index"
  get "/sell", to: "bills#new"
  get "/new-product", to: "home#new"
  get "/reset-seq", to: "home#reset_seq"
  
  get "/products/add-items", to: "home#create"
  resources :transactions do
    collection do
      get :all
    end
  end
  resources :debts, only: [:index, :update, :edit, :destroy]
  resources :items
  resources :sales do
    collection do
      get :all
    end
  end
  resources :bills do
    collection do
      get :search
    end
  end
  resources :products
  resources :charges, only: [:index, :show, :new, :create]
  resources :clients
  # get "/importer", to: "bills#importer"
  # post "/import", to: "bills#import"
end

app/models/bill.rb
class Bill < ApplicationRecord
    has_many :sales, dependent: :destroy
    has_one :debt
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :authenticate_user!, except: %i[importer import]
  before_action :set_bill, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token, only: %i[ create ]

  def search
    if params[:q]
      @bills = Bill.where(id: params[:q]).or(Bill.where(buyer: params[:q]))
    end
  end
  

  # GET /bills/1 or /bills/1.json
  def show
    @bill = Bill.includes(:sales).find(params[:id])
  end

  # GET /bills/new
  def new
    @bill = Bill.new
    @products = Product.all.select(:id, :name, :selling_price, :whole_sale_price).order(:name)
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills or /bills.json
  def create
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, OPTIONS'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
    notes = ""
    @store = Store.first
    buyer = params['buyer'] ? params['buyer'] : nil
    paid_amount = params['paid_amount'] ? params['paid_amount'].to_i : nil
    seller = current_user.email
    @bill = Bill.create(buyer: buyer)
    @bill.seller = seller
    bill_count = 0
    params.to_enum.each_with_index do |pair, index|
      is_sale = pair[0] =~ /sale_[0-9]/
      if is_sale == 0
        # Extract values
        i =  index + 1
        discount = (pair[1]["sale#{i}[discount]"] ? pair[1]["sale#{i}[discount]"] : 0).to_i
        quantity = (pair[1]["sale#{i}[quantity]"]).to_i
        product_id = pair[1]["sale#{i}[id]"]
        product = Product.find(product_id)
        item = Item.where(product_id: product_id).order('created_at ASC').first
        price_to_use = pair[1]["sale#{i}[type]"] === "selling_price" ? product.selling_price : product.whole_sale_price

        sale_type = pair[1]["sale#{i}[type]"] === "selling_price" ? "جمهور" : "جملة"
        
        # Create sale
        sale = Sale.new(bill_id: @bill.id, product_id: product_id, quantity: quantity, name: product.name, buying_price: item.buying_price, selling_price: price_to_use, validity: product.validity, discount: discount, sale_type: sale_type)

        # If a valid sale ==> Add to bill
        if quantity <= product.items.count
          if sale.save
            bill_count += 1
            if @bill.total
              @bill.total = @bill.total + price_to_use * quantity - discount
            else
              @bill.total = price_to_use * quantity - discount
            end
            quantity.times do
              item = Item.where(product_id: product_id).order('created_at ASC').first
              item.destroy
            end
            product.quantity -= quantity
            product.save
          else
            redirect_to '/sell', notice: 'حدث خطأ مجهول!'
          end
        else
          notes += "الكمية التي تريد بيعها من #{product.name} ليست متاحه في المخزن. || "
        end
      end
    end

    # Handle Store Selling Dorge && Save
    @store.dorg += @bill.total

    if paid_amount && @bill.total > paid_amount
      Debt.create(debtor: buyer, bill_id: @bill.id, dept_value: @bill.total - paid_amount)
      @store.dorg -= @bill.total - paid_amount
    end

    if bill_count == 0
      @bill.destroy
    else
      @store.save
      @bill.save
    end

    render json: {message: "Saved"}
  end



  # PATCH/PUT /bills/1 or /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: "Bill was successfully updated." }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1 or /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: "Bill was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def importer
  end

  def import
    require 'csv'    


    CSV.foreach(params[:csv_file].path, headers: true) do |row|
      Sale.create! row.to_hash
    end

    format.html { redirect_to importer, notice: "imported...!" }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bill_params
      params.require(:bill).permit(:total, :buyer)
    end
end

app/views/bills/importer.html.erb
<h1>importer</h1>
<p id="notice" class="text-center"><%= notice %></p>

<%= form_with url: "/import", method: :post do |form| %>
  <%= form.file_field :csv_file %>
  <%= form.submit "Import" %>
<% end %>

app/views/bills/new.html.erb
<h1 class="text-center mb-3">عملية بيع جديدة</h1>

<%= react_component('App', {products: @products}) %>

app/views/bills/search.html.erb
<h1 class="text-center mb-3">Computech</h1>

<div class="max-width">
    <form method="GET" action="/bills/search" >
        <input type="text" name='q' placeholder="ابحث باستخدام اسم صاحب الفاتورة أو رقم الفاتورة" class="form-control" />
        <input type="submit" value="بحث" class="btn bg-gradient white m-2" />
    </form>


    
    <% if @bills %>
        <table class="table table-bordered table-sm table-striped max-width">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">رقم الفاتورة</th>
                    <th scope="col">صاحب الفاتورة</th>
                    <th scope="col">البائع</th>
                    <th scope="col">تاريخ البيع</th>
                    <th scope="col">عرض الفاتورة</th>
                </tr>
            </thead>

            <tbody>
                <% @bills.each do |bill| %>
                <tr scope="row">
                    <td><%= bill.id %></td>
                    <td><%= bill.buyer %> </td>
                    <td><%= bill.seller %></td>
                    <td><%= bill.created_at.strftime('%F || %I:%M || %p') %></td>
                    <td><%= button_to "تفاصيل الفاتورة" , bill_path(bill.id), method: "get", class:"btn blue-link" %></td>
                </tr>
                <% end %>
            </tbody>
        </table>
    <% end %>
</div>

app/views/bills/show.html.erb
<h1 class="text-center mb-3">Computech</h1>
<div class="text-center mt-3 d-flex justify-content-between max-width p-2">
  <p>
    <span> التاريخ: </span>
    <span> <%= @bill.created_at.strftime('%d/%m/%Y') %></span>
    <br/>
    <span> الساعة: </span>
    <span> <%= @bill.created_at.strftime('%I %p') %></span>
  </p>
</div>


<div class="text-center mt-3 d-flex justify-content-between max-width p-2">
  <h5>
    <span> اسم المشتري: </span>
    <span> <%= @bill.buyer %></span>
  </h5>
  <h5>
    <span> الفاتورة رقم: </span>
    <span> <%= @bill.id %> </span>
  </h5>
  <h5>
    <span> مجمل سعر الفاتورة: </span>
    <span> <%= @bill.sales.sum('(selling_price * quantity) - discount') %> ج.م</span>
  </h5>
</div>



<div class="text-center mb-2 d-flex justify-content-between max-width p-2">
  <%if @bill.debt %>
    <h5>
      <span> الحالة : </span>
      <span>ناقصة الحساب </span>
    </h5>
    <h5>
      <span> الباقي : </span>
      <span> <%= @bill.debt.dept_value %> ج.م</span>
    </h5>
    <h5>
      <span> المدفوع : </span>
      <span> <%= @bill.sales.sum('(selling_price * quantity) - discount') - @bill.debt.dept_value %> ج.م</span>
    </h5>
  <% else %>
    <h5>
      <span> الحالة : </span>
      <span> مدفوعة كاملا</span>
    </h5>
    <h5>
      <span>المدفوع : </span>
      <span> <%= @bill.sales.sum('(selling_price * quantity) - discount') %> ج.م</span>
    </h5>
  <% end %>
  
</div>




<table class="table table-bordered table-sm table-striped max-width">
  <thead class="thead-dark">
    <tr>
      <th scope="col">الاسم</th>
      <th scope="col">الكمية</th>
      <th scope="col">سعر بيع القطعة</th>
      <th scope="col">المجمل</th>
      <th colspan="2">ادارة</th>
    </tr>
  </thead>

  <tbody>
    <% @bill.sales.each do |sale| %>
      <tr scope="row">
        <td><%= sale.name %></td>
        <td><%= sale.quantity %></td>
        <td><%= sale.selling_price %> ج.م</td>
        <td><%= sale.quantity * sale.selling_price - sale.discount %> ج.م</td>
        <% if current_user.admin %>
          <td><%= link_to 'تعديل', edit_sale_path(sale), class:"btn bg-gradient-secondary white p-1" %></td>
          <td><%= link_to 'عمل مرتجع', sale, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn bg-gradient-danger white p-1"%></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="text-center">
  <%= link_to 'الرجوع', sales_path, class:"btn btn-secondary" %>
</div>