config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "sales#index"
  get "/sell", to: "bills#new"
  get "/new-product", to: "home#new"
  get "/reset-seq", to: "home#reset_seq"
  
  get "/products/add-items", to: "home#create"
  resources :transactions do
    collection do
      get :all
    end
  end
  resources :debts, only: [:index, :update, :edit, :destroy]
  resources :items
  resources :sales do
    collection do
      get :all
    end
  end
  resources :bills do
    collection do
      get :search
    end
  end
  resources :products
  resources :charges, only: [:index, :show, :new, :create]
  resources :clients
  # get "/importer", to: "bills#importer"
  # post "/import", to: "bills#import"
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_transaction, only: %i[ show edit update destroy ]

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.order('created_at desc')
  end

  def all
  end
  

  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create
    @store = Store.first
    @transaction = Transaction.new(transaction_params)
    @transaction.dorg_was = @store.dorg

    if @transaction.transaction_type == 'decrease'
      @store.dorg -= @transaction.transaction_value
    else
      @store.dorg += @transaction.transaction_value
      if @transaction.title == 'فودافون كاش'
        p 'heeeeeeeeeeeeeeeey'
        @sale = Sale.new(name: 'فودافون كاش', buying_price: 0, selling_price: @transaction.transaction_value, quantity: 1, seller: current_user.email, bill_id: Bill.first.id, product_id: Product.first.id)
        @sale.errors.full_messages
      end
    end

    respond_to do |format|
      if @transaction.save
        if @sale
          @sale.save
        end
        @store.save
        format.html { redirect_to transactions_url, notice: "تمت المعاملة بنجاح." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transactions_url, notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "Transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:title, :transaction_value, :dorg_was, :notes, :transaction_type)
    end
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if params[:type] == 'increase' %>
    <div class="field form-group">
      <%= form.label 'المعاملة' %>
      <input type="hidden" value="increase" name="transaction[transaction_type]" />
      <%= select_tag "transaction[title]", options_for_select([ "فودافون كاش", "صيانة" ,"استثمار" ,"أخرى"]), class:"form-control", prompt: "اختر المعاملة", required: true %>
    </div>
  <% else %>
    <div class="field form-group">
      <%= form.label 'المعاملة' %>
      <input type="hidden" value="decrease" name="transaction[transaction_type]" />
      <%= select_tag "transaction[title]", options_for_select([ "دفع عمالة", "دفع كهرباء", "دفع الإيجار", "دفع ضرايب" ,"أخرى"]), class:"form-control", prompt: "اختر المعاملة", required: true %>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label 'القيمة' %>
    <%= form.number_field :transaction_value, class:"form-control" , step: :any, required: true %>
  </div>

  <div class="field form-group">
    <%= form.label 'تفاصيل' %>
    <%= form.text_field :notes, class:"form-control" ,  required: true %>
  </div>

  <div class="actions">
    <%= form.submit 'إجراء المعاملة', class: "bg-gradient white btn" %>
  </div>
<% end %>

app/views/transactions/all.html.erb
<h1 class="text-center mb-3">
    إدارة الدرج
</h1>

<div class="row">
    <div class="col-6">
        <a href="/transactions/new?type=increase">
            <i class="fa fa-download big-icon white"></i>
            <h6 class="bg-gradient-tertiary white p-1 py-3 m-2 text-center rounded">
                إيداع في الدرج (صيانة - استثمار - شيء اخر)
            </h6>
        </a>
    </div>

    <div class="col-6">
        <a href="/transactions/new?type=decrease">
            <i class="fa fa-upload big-icon white"></i>
            <h6 class="bg-gradient-secondary white p-1 py-3 m-2 text-center rounded">
                سحب من الدرج (عمالة - كهرباء - ضرايب - شيء اخر)
            </h6>
        </a>
    </div>

    <div class="col-12">
        <a href="/transactions">
            <i class="fa fa-download big-icon white"></i>
            <h6 class="bg-gradient white p-1 py-3 m-2 text-center rounded">
                عرض جميع المعاملات
            </h6>
        </a>
    </div>
</div>

<div class="container my-2">
  <%= link_to 'الغاء و عودة', root_path, class:"btn btn-secondary" %>
</div>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1 class="text-center mb-3">
  المعاملات 
</h1>
<td><%= link_to 'رجوع للخلف', all_transactions_path, class: "btn btn-secondary m-3" %></td>

<table class="table table-bordered table-sm table-striped max-width">
  <thead class="thead-dark">
    <tr>
      <th scope="col">المعاملة</th>
      <th scope="col">قيمة المعاملة</th>
      <th scope="col">التفاصيل</th>
      <th scope="col">الدرج قبل المعاملة</th>
      <th scope="col">الدرج بعد المعاملة</th>
      <th scope="col">التاريخ</th>
      <%# <th scope="col"></th> %>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr scope="row">
        <td><%= transaction.title %></td>
        <td><%= transaction.transaction_value %></td>
        <td><%= transaction.notes %></td>
        <td><%= transaction.dorg_was %></td>
        
        <% if transaction.transaction_type == 'decrease' %>
          <td><%= transaction.dorg_was - transaction.transaction_value %></td>
          <% else %>
          <td><%= transaction.dorg_was + transaction.transaction_value %></td>
        <% end %>
        <td><%= transaction.created_at.strftime('%F || %I:%M || %p') %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/transactions/new.html.erb
<% if params[:type] == 'increase' %>
<h1 class="text-center mb-3">
  معاملة إيداع
</h1>
<% else %>
<h1 class="text-center mb-3">
  معاملة سحب
</h1>
<% end %>


<div class="max-width">
  <%= render 'form', transaction: @transaction %>
  <br>
  <%= link_to 'إلغاء و رجوع', transactions_path %>
</div>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @transaction.title %>
</p>

<p>
  <strong>Transaction value:</strong>
  <%= @transaction.transaction_value %>
</p>

<p>
  <strong>Dorg was:</strong>
  <%= @transaction.dorg_was %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>