config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "sales#index"
  get "/sell", to: "bills#new"
  get "/new-product", to: "home#new"
  get "/reset-seq", to: "home#reset_seq"
  
  get "/products/add-items", to: "home#create"
  resources :transactions do
    collection do
      get :all
    end
  end
  resources :debts, only: [:index, :update, :edit, :destroy]
  resources :items
  resources :sales do
    collection do
      get :all
    end
  end
  resources :bills do
    collection do
      get :search
    end
  end
  resources :products
  resources :charges, only: [:index, :show, :new, :create]
  resources :clients
  # get "/importer", to: "bills#importer"
  # post "/import", to: "bills#import"
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :sales
    has_many :items, dependent: :destroy

    validates :selling_price, presence: true
    validates :whole_sale_price, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: %i[ show edit update destroy ]
  
  # GET /products or /products.json
  def index
    @products = Product.all.order('name')
  end

  # GET /products/1 or /products/1.json
  def show
    @product = Product.includes(:items).find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
    @product.validity = Date.today.next_year
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @store = Store.first
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        params[:product]['quantity'].to_i.times do
          Item.create(product_id: @product.id, buying_price: params[:product]['buying_price'])
          @store.dorg -= params[:product]['buying_price'].to_i
        end
        @store.save
        format.html { redirect_to '/products/new', notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :selling_price, :whole_sale_price, :quantity, :validity)
    end
end

app/views/products/edit.html.erb
<h1 class="text-center mb-3">تعديل المنتج</h1>

<%= form_with(model: @product, class:"container") do |form| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% @product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="field form-group">
    <%= form.label "اسم المنتج" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label "سعر البيع" %>
    <%= form.number_field :selling_price, class:"form-control" , step: :any %>
  </div>

  <div class="field form-group">
    <%= form.label "سعر بيع الجملة" %>
    <%= form.number_field :whole_sale_price, class:"form-control" , step: :any %>
  </div>

  <div class="actions">
    <%= form.submit "تعديل المنتج", class:"btn bg-gradient-tertiary white", data: { disable_with: "انتظر..." } %>
  </div>
<% end %>



<div class="container mt-5">
    <%= link_to 'عرض المنتج', @product, class:"btn bg-gradient-secondary white" %> |
    <%= link_to 'رجوع للخلف', products_path, class:"btn btn-secondary" %>
</div>

app/views/products/index.html.erb
<h1 class="text-center mb-3">المنتجات</h1>

<div class="text-center mb-2">
  <%= link_to 'اضافة منتج +', new_product_path,  class:"btn bg-gradient-tertiary white" %>
  <button onclick='printDiv("table")'>طباعة</button>
</div>
<div class="container my-2">
    <%= link_to 'رجوع للخلف', root_path, class:"btn btn-secondary" %>
</div>
<table class="table table-bordered table-sm table-striped max-width">
  <thead class="thead-dark">
    <tr>
      <th scope="col">الاسم</th>
      <th scope="col">سعر البيع</th>
      <th scope="col">سعر الجملة</th>
      <th scope="col" small='true'>الكمية في المخزن</th>
      
    </tr>
  </thead>

  <tbody id='table'>
    <% @products.each do |product| %>
      <tr scope="row">
        <td><%= product.name %></td>
        <td><%= product.selling_price %> ج.م</td>
        <td><%= product.whole_sale_price %> ج.م</td>
        <td><%= product.items.count %> قطعة</td>
        <% if current_user.admin %>
          <td><%= link_to 'عرض البضاعة', product, class:"btn bg-gradient-tertiary white" %></td>
          <td><%= button_to 'حذف المنتج نهائيا', product, method: :delete, data: { confirm: 'هل أنت متأكد ؟' }, class:"btn bg-gradient-danger white" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<script>
 function printDiv(divID) {
        //Get the HTML of div
        var divElements = document.getElementById(divID).innerHTML;
        //Get the HTML of whole page
        var oldPage = document.body.innerHTML;
        //Reset the page's HTML with div's HTML only
        document.body.innerHTML = 
          "<html><head> <link rel='stylesheet' href='https://cdn.rtlcss.com/bootstrap/v4.5.3/css/bootstrap.min.css' integrity='sha384-JvExCACAZcHNJEc7156QaHXTnQL3hQBixvj5RV5buE7vgnNEzzskDtx9NQ4p6BJe' crossorigin='anonymous'></head><body>" + 
          divElements + "</body>";
        //Print Page
        window.print();
        //Restore orignal HTML
        document.body.innerHTML = oldPage;
    }
</script>

app/views/products/new.html.erb
<h1 class="text-center mb-3">
    اضافة منتج جديد
</h1>

<%= form_with(model: @product, class:"container") do |form| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% @product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="field form-group">
    <%= form.label "اسم المنتج" %>
    <%= form.text_field :name, class:"form-control", required: true %>
  </div>

  <div class="field form-group">
    <%= form.label "سعر الشراء" %>
    <%= form.number_field :buying_price, class:"form-control" , step: :any, required: true %>
  </div>

  <div class="field form-group">
    <%= form.label "سعر البيع" %>
    <%= form.number_field :selling_price, class:"form-control" , step: :any, required: true %>
  </div>

  <div class="field form-group">
    <%= form.label "سعر بيع الجملة" %>
    <%= form.number_field :whole_sale_price, class:"form-control" , step: :any, required: true %>
  </div>

  <div class="field form-group">
    <%= form.label "الكمية المراد ادخالها" %>
    <%= form.number_field :quantity, class:"form-control", required: true %>
  </div>

  <div class="actions">
    <%= form.submit "اضافة المنتج", class:"btn bg-gradient-tertiary white", data: { disable_with: "انتظر..." } %>
  </div>
<% end %>

<div class="container mt-2">
    <%= link_to 'رجوع للخلف', root_path, class:"btn btn-secondary" %>
</div>

app/views/products/show.html.erb
<div class="text-center p-3 mb-3">
    <h1><%= @product.name %></h1>
</div>

<div class="row p-3 text-center max-width flex-row justify-between">
  <% if current_user.admin %>
    <%= link_to 'تعديل بيانات المنتج', edit_product_path(@product), class:"btn bg-gradient-secondary white" %>
  <% end %>
  <%= link_to 'الرجوع للخلف', products_path, class:"btn bg-secondary white" %>
</div>

<div class="row p-3 text-center max-width bg-gradient-tertiary btn-dark">
  <h4 class="col-6">الكمية</h4>
  <h4 class="col-6"><%= @product.items.count %></h4>
</div>

<div class="row p-3 text-center max-width">
  <h4 class="col-6">سعر بيع الوحدة</h4>
  <h4 class="col-6"><%= @product.selling_price %></h4>
</div>

<div class="row p-3 text-center max-width bg-gradient-tertiary btn-dark">
  <h4 class="col-6">سعر بيع الجملة</h4>
  <h4 class="col-6"><%= @product.whole_sale_price %></h4>
</div>


<table class="table table-bordered table-sm table-striped max-width mt-4">
  <thead class="thead-dark">
    <tr>
      <th scope="col">رقم الوحدة</th>
      <% if current_user.admin %>
        <th scope="col">سعر الشراء</th>
      <% end %>
      <th scope="col">تاريخ الادخال</th>
    </tr>
  </thead>

  <tbody>
    <% @product.items.each do |item| %>
      <tr scope="row">
        <td><%= item.id %></td>
        <% if current_user.admin %>
          <td><%= item.buying_price %> ج.م</td>
        <% end %>
        <td><%= item.created_at.strftime('%F - %I:%M - %p') %></td>
        <!-- <td><%= button_to 'تعديل', edit_item_path(item.id), method: :get, class:"btn bg-gradient-secondary white" %></td> -->
        <% if current_user.admin %>
          <td><%= button_to 'تالف مردود الثمن', {:controller => "items", :action => "destroy", :money_back => true, :id => item.id}, method: :delete,  data: { confirm: 'هل أنت متأكد ؟' }, class:"btn btn-secondary" %></td>
          <td><%= button_to 'تالف هدر', item, method: :delete, data: { confirm: 'هل أنت متأكد ؟' }, class:"btn bg-gradient-danger white" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>